Добавляю функции расчета случайных чисел
htmlacademy-javascript/1756921-keksobooking-24 pull request #2
Opened 2021-09-26 08:17 UTC by Liandus

2021-09-26 11:31 UTC, ianikitin requested changes
Отличный темп! Функции работают. Оставил немного комментариев, давай доделаем, чтобы стало 🔥

2021-09-26 11:31 UTC, ianikitin commented on js/main.js
> +  if((from%1 === 0) || (to % 1 === 0)){
Давай не забыть про форматирование и добавим пробелы, где это необходимо. На работоспособность кода это не влияет, но это как красивый почерк - читать легче, приятнее. \
_Посмотри во всем файле, есть еще такие места._

В будущем, на реальных проектах могут использоваться специальные плагины (например prettier). Они автоматически будут форматировать код. Но лучше привыкать сразу писать красиво и поднимать свой профессиональный уровень :)

2021-09-26 11:31 UTC, ianikitin commented on js/main.js
> +  number = (Math.random() * (to - from)) + from;
Если на 31 строке условие будет true, то мы выполним присваивание случайного числа в переменную number на 32 строке. Потом программа пойдет дальше (мы ее не прерываем) и дойдет до 34 строки, где перепишет переменную number. Как думаешь, можно ли как-то упростить здесь получение случайного числа?

2021-09-26 11:31 UTC, ianikitin commented on js/main.js
> +"use strict";
Мы подключаем .js файл как [модуль](https://github.com/htmlacademy-javascript/1756921-keksobooking-24/blob/953b55e88a5ff6f7c600f0f902cf86e23e7b179a/.eslintrc#L5), 'use strict' не нужен.

2021-09-27 07:15 UTC, inikitinfbs requested changes
Сейчас функция `isIncorrectRange` не возвращает значение false. Тестируя функцию у тебя могло работать все правильно, т.к результат функции, которая ничего не вернула был равен undefined (что не true). Но это особенности динамической типизации JavaScript. Нужно явно возвращать ожидаемое значение.

2021-09-27 07:15 UTC, inikitinfbs commented on js/main.js
> +  }
А как получить false? :) Сейчас мы возвращаем результат только при положительном условии `max <= min || min < 0)`.

2021-09-27 07:15 UTC, inikitinfbs commented on js/main.js
> +  // return (max <= min || min < 0) ? true : false;
Уже лучше, вернем либо true, либо false. Но тут есть крутой момент, о нем вчера говорили: 
результат выполнения `(max <= min || min < 0)` уже boolean, и вернув его мы вернем нужное значение (true или false).

2021-09-27 09:47 UTC, merged

2021-09-27 09:48 UTC, ianikitin commented on js/main.js
> +const isIncorrectRange = (min, max) => (max <= min || min < 0);
Красиво получилось. 🔥