Обработка и отправление данных на сервер
htmlacademy-javascript/1756921-keksobooking-24 pull request #8
Opened 2021-11-05 15:01 UTC by Liandus

2021-11-05 15:11 UTC, Liandus commented on js/forms-popups.js
> +const showPopup = (template) => {
Касательно этой функции есть вопросы, я сделал ее универсальной что бы  показывать и окно успеха и окно ошибки. как раз по этой причине ну во всяком случае мне так кажется, я не смогу придумать грамотного способа разбить на участки ее, ну то есть у меня функция называется showPopup  а внутри не только показываю, но и удаляю попап. вроде в голове у себя  я  придумал способ но тогда придется отказаться от  универсальности, то есть сделать  showSuccessPopup, closeSuccessPopup, showErrorPopup, closeErrorPopup. тогда возможность удалить обработчики событий появится и тд. я короче запутался немного) нужен совет как поступить

2021-11-05 15:13 UTC, Liandus commented on js/forms.js
> +    () => showSuccessPopup(),
() =>  не совсем понимаю почему приходится вызывать функцию которая вызывает функцию. принцип работы взял с демки академии.

2021-11-05 15:16 UTC, Liandus commented on js/server-api.js
> +  /*.catch(() => {
при успехе у меня появляется попап,  при неудаче появляется другой попап. я не совсем понимаю нужен ли здесь кетч, если нужен то что ему ловить тут, подскажи пожалуйста

2021-11-05 15:59 UTC, ianikitin requested changes

2021-11-05 15:59 UTC, ianikitin commented on css/style.css
> +
Обрати внимание на отступы.

2021-11-05 15:59 UTC, ianikitin commented on js/forms-popups.js
> +const showPopup = (template) => {
Не, все норм. Ты явно его не удаляешь тут. Ты показываешь, и навешиваешь обработчики на возможные действия. Все отлично. 
Я бы только пересмотрел нейминг функций `closePopup` и `addPopup`. Они делают ровно противоположные действия, поэтому я бы называл тоже синонимами: 
addPopup/removePopup или openPopup/closePopup

2021-11-05 15:59 UTC, ianikitin commented on js/forms.js
> +    () => showSuccessPopup(),
А как не получалось?

2021-11-05 15:59 UTC, ianikitin commented on js/forms.js
> +};
Давай preventDefault перенесем сюда, т.к именно эта функция в обработчике и вызывается при клике, а в submitForm оставим непосредственно логику, связанную с отправкой формы. Тогда `submitForm()` будет чуть универсальнее. Вдруг отправка формы будет не только по нажатию на кнопку, и там предотвращать ничего не надо.

2021-11-05 15:59 UTC, ianikitin commented on js/server-api.js
> +  'https://24.javascript.pages.academy/keksobooking/data',
Давай в константу URL кинем?

2021-11-05 15:59 UTC, ianikitin commented on js/server-api.js
> +  /*.catch(() => {
Поймает ошибку с сервером, например если сервер не ответит, интернет потеряется и т.д.

2021-11-05 15:59 UTC, ianikitin commented on js/utils/error-message.js
> +const MESSAGE_SHOW_TIME = 5000;
👍

2021-11-05 15:59 UTC, ianikitin commented on js/forms-popups.js
> +  });
Нужно обязательно отписаться после закрытия. Иначе при каждом открытии попапа будет добавлять новый слушатель.
![Кексобукинг — Яндекс Браузер 2021-11-05 18 53 00](https://user-images.githubusercontent.com/39906730/140539789-f87456aa-85d6-453b-a53d-cc643b34f7c7.png)

2021-11-05 15:59 UTC, ianikitin commented on js/forms-popups.js
> +  tryAgainButtonEl.addEventListener('click', () => {
У меня после показа попапа ошибка вылезла. Проверь, что элемент существует когда определяется
![Кексобукинг — Яндекс Браузер 2021-11-05 18 49 08](https://user-images.githubusercontent.com/39906730/140539294-e760bdd5-2f40-492a-9f71-9877f62f7bf7.png)
.

2021-11-05 15:59 UTC, ianikitin commented on js/forms-popups.js
> +  tryAgainButtonEl.addEventListener('click', () => {
После закрытия попапа если нажать на кнопку "Очистить" тоже ошибка в консоли
![Кексобукинг — Яндекс Браузер 2021-11-05 18 50 52](https://user-images.githubusercontent.com/39906730/140539472-082a77ec-df62-473e-9330-4207f9ac582e.png)
:

2021-11-05 15:59 UTC, ianikitin commented on js/server-api.js
> +  /*.catch(() => {
Обязательно по условию надо: https://up.htmlacademy.ru/javascript/24/project/keksobooking#keksobooking-2-7
Можешь проверить работу сэмулировав отсутствие интернета в DevTools:
![Кексобукинг — Яндекс Браузер 2021-11-05 18 57 56](https://user-images.githubusercontent.com/39906730/140540538-3e4ffc4a-0082-4379-a19b-a8d04886d84a.png)

2021-11-05 15:59 UTC, ianikitin commented on js/utils/error-message.js
> +const showMessage = (message) => {
любой message или только error? Стоит уточнить в названии. Вызывая функцию в других модулях будет не ясно.

2021-11-06 22:04 UTC, Liandus commented on js/forms-popups.js
> +
Упустил пробел, вижу)) поправил)

2021-11-06 22:06 UTC, Liandus commented on js/forms-popups.js
> +const showPopup = (template) => {
Переделал данную функцию, смог добиться только такого результата, не приходит в голову пока как ее уменьшить.

2021-11-06 22:08 UTC, Liandus commented on js/server-api.js
> +
тоже пробел не особо нужен)

2021-11-06 22:11 UTC, Liandus commented on js/server-api.js
> +    .catch((err) => {
если допустим я изменяю адрес сервера, все срабатывает, если как ты посоветовал имитирую отключения интернета, не вылезает попап, не представляю пока как обработать ошибку "нет интернета", попробую конечно  поискать в инете, но от подсказки не откажусь)

2021-11-07 13:50 UTC, ianikitin commented on js/forms-popups.js
> +const showPopup = (template) => {
Да никак особо не уменьшить. Можно вынести из нее функции, но смысла особо нет, отдельно они все равно не нужны.

2021-11-07 14:39 UTC, ianikitin commented on js/forms-popups.js
> +  openPopup ();
https://learn.javascript.ru/coding-style#sintaksis Поправь, пожалуйста, по стайлгайду.

2021-11-07 14:39 UTC, ianikitin commented on js/forms-popups.js
>    });
Давай уберем фигурные скобки и сделаем в одну строку? Будет красиво :)

2021-11-08 19:33 UTC, Liandus commented on js/map.js
> +const ADVERTISEMENT_COUNT =10;
вижу помарку, исправлю)

2021-11-09 09:10 UTC, merged