Фильтрация меток на карте
htmlacademy-javascript/1756921-keksobooking-24 pull request #9
Opened 2021-11-10 14:33 UTC by Liandus

2021-11-10 16:07 UTC, ianikitin commented on js/filter.js
> +};
Через наследование и querySelectorAll можно повесить на все нужные элементы одной строчко

2021-11-10 16:24 UTC, ianikitin requested changes

2021-11-10 16:24 UTC, ianikitin commented on js/filter.js
> +};
Частично дублируют друг друга. Получится объединить?

2021-11-10 16:24 UTC, ianikitin commented on js/map.js
>  import {showAdvertisement} from './advertisements.js';
Из ТЗ:
_Обратите внимание, что в неактивное состояние форма фильтрации переключается вместе с остальными элементами страницы, но активируется только при успешной загрузке объявлений и инициализации карты, иначе что фильтровать и где?_

Сейчас это условие не выполняется и форма активна раньше появления объявлений и инициализации карты.

2021-11-10 16:24 UTC, ianikitin commented on js/filter.js
> +import {markerGroup} from './map.js';
Не выполнено условие из ТЗ: 
_Воспользуйтесь приёмом «устранение дребезга», чтобы при переключении фильтра обновление меток, подходящих под фильтры, происходило не чаще, чем один раз в полсекунды._

2021-11-10 16:24 UTC, ianikitin commented on js/filter.js
> +const getAdvertisementRank = (advertisement) => {
В ТЗ, кстати, про сортировку ничего не сказано. 
Из ТЗ:
_Все выбранные фильтры применяются вместе: один фильтр не отменяет другие, выбранные до него. Например, после выбора типа жилья можно указать диапазон стоимости и удобства, в таком случае **на карте должны показываться только те метки, которые удовлетворяют всем фильтрам сразу**. Как в изначальном состоянии, так и при изменении фильтров, на карте должно показываться не более 10 меток._

2021-11-10 16:24 UTC, ianikitin commented on js/filter.js
> +const housingTypeEl = document.querySelector('#housing-type');
Что-то не так. Выбрал бунгало, а показывает дворец. 
<img width="908" alt="Screenshot 2021-11-10 at 19 23 06" src="https://user-images.githubusercontent.com/39906730/141151905-d78678b5-8e92-4a75-930e-2fe3cc791427.png">

2021-11-10 16:24 UTC, ianikitin commented on js/filter.js
> +const housingTypeEl = document.querySelector('#housing-type');
И комнаты не всегда правильные предлагает. 
<img width="509" alt="Screenshot 2021-11-10 at 19 24 22" src="https://user-images.githubusercontent.com/39906730/141152045-c9d923cd-6625-4027-9089-483fadef02ef.png">

2021-11-11 01:05 UTC, Liandus commented on js/map.js
>  import {showAdvertisement} from './advertisements.js';
Проверял через медленный 3g, скрипты не загружаются очень долго поэтому форма активна а должна работать функция deactivateForm(); единственное что я придумал изначально поставить все как надо в html и активировать при загрузке карты, тут тоже есть ньюанс - да же в таком случае  карта грузится и через пол секунды только метки появляются) если есть решение я весь внимание)

2021-11-11 01:12 UTC, Liandus commented on js/filter.js
> +};
вот тут честно я не понял, я могу конечно 15-20 строку удалить и использовать информацию из перечислений, но тогда  я буду  делать так допустим: 
case NameRoomsValue.ONE_ROOM:
      if (Number(rooms) === NameRoomsValue.ONE_ROOM) {
        return dataEl;
      }
      break; 
мне кажется это немного не логичным,  но если так можно я поправлю) если ты это в целом имел ввиду)

2021-11-11 01:18 UTC, Liandus commented on js/filter.js
> +import {markerGroup} from './map.js';
подключал библиотеку лодэш, пробовал по разному debounce использовать,  так и не получилось, либо не отрисовывались метки совсем, либо просто ничего не происходило) уже почти утро я ничего не соображаю возможно)

2021-11-11 12:46 UTC, Liandus reviewed
с активацией и деактивацией попрежнему нужна помощь) не знаю как поступить по другому) если пытаюсь внедрить другую логику нежели у меня, вообще все не правильно начинает работать)

2021-11-11 12:46 UTC, Liandus commented on js/main.js
> +dataLoad(loadToMarkers, showErrorMessage);
не имея опыта не знаю что надо вынести в main.js, придумал для себя такую схему у меня на странице две области карта и форма обьявления, значит в мейне будет функция которая отвечает за загрузку, через которую работает фильтрация и тд. и функция submitListener() (ниже) которая ждет самбит на форме обьявления, и ловит всю валидацию и тд.
если я не правильно думаю, поправь меня пожалуйста

2021-11-11 12:49 UTC, Liandus commented on js/forms.js
> +//formEl.addEventListener('submit', onSubmit);
вижу косяк, тестировал забыл удалить каюсь)

2021-11-11 14:35 UTC, ianikitin commented on package.json
> +    "lodash": "^4.17.21"
Нужно зафиксировать версию. Критерий Б13.

2021-11-11 14:35 UTC, ianikitin commented on js/filter.js
> +import {markerGroup} from './map.js';
Смотрю, что в итоге получилось?

2021-11-11 14:35 UTC, ianikitin commented on js/filter.js
> +      if (advertisementFeatures && advertisementFeatures.includes(feature.value)) {
Можно объединить в один if, а для читаемости вынести в функцию или переменную.

2021-11-11 14:35 UTC, ianikitin commented on js/filter.js
> +      break;
В switch case хорошим тоном будет добавить default для обработки "иных" случаев.

2021-11-11 14:35 UTC, ianikitin commented on js/main.js
> +dataLoad(loadToMarkers, showErrorMessage);
Представь main.js как ресепшн в отеле. Он тебя встретит, расскажет, куда идти дальше, что делать дальше, но не более того. Остальная логика (проживание, бар, бассейн) - в отдельных помещениях/модулях :)

2021-11-11 14:35 UTC, ianikitin commented on js/map.js
>  import {showAdvertisement} from './advertisements.js';
Даже если deactivateForm в main.js? 

_>  если есть решение я весь внимание)_
Не очень понял, решение чего?

2021-11-11 14:38 UTC, ianikitin commented
По упавшим тестам, проверь, что задание выполнено в полном объеме: https://up.htmlacademy.ru/javascript/24/check/tasks/1756921/20
И все utils из мастера есть у тебя в ветке. Тогда ты там сможешь поправить ошибки.

2021-11-11 16:54 UTC, Liandus commented on js/filter.js
> +import {markerGroup} from './map.js';
лодэш неадекватно как то работал, я по ютубу написал свою debounce функцию и воспользовался ею в итоге)

2021-11-12 00:47 UTC, Liandus commented on js/main.js
> +deactivateForm();
перенес deactivateForm() в мейн, удалил disabled  и нужные классы с форм, короче если, атрибуты и классы удалены, то все по-прежнему сначала грузится html и css, форма активна, потом только начинает работать deactivateForm(). можно закоментить loadMap(activateForm()); и убедится на маленькой скорости.
если атрибуты и классы повешены, то формы активируются после загрузки карты, единственное что она раньше появления меток активной становится, я пробовал по разному это исправить но так и не нашел способ.
 в итоге я не знаю как обойтись без навешивания атрибутов изначально, нужен дельный совет) или можно оставить вариант с навешиванием атрибутов? вроде это не запрещено?

2021-11-12 00:48 UTC, Liandus commented on js/main.js
> +dataLoad(loadToMarkers, showErrorMessage);
ну вот такой вариант как сейчас у меня это нормально? или как то надо переработать?

2021-11-12 00:52 UTC, Liandus commented on package.json
> +    "lodash": "4.17.21"
короче случайно, не спрашивай как))) перенес lodash в devDependencies, это ничего? я в принципе вообще не пользуюсь им могу удалить)

2021-11-12 07:11 UTC, ianikitin commented on js/main.js
> +deactivateForm();
На супер маленькой скорости конечно, так и будет. Все загружается сверху, поэтому сначала подгружается html, потом подключенный js. Подключение js можно вынести в head, но его загрузка может занять время, и все это время будет белая страница, что не ок. Можно добавить аттрибут async, для аиснхронной загрузки, но там будут нюансы. Поэтому да, в контексте этой задачи решение с изначально заблокированной версткой ок.

2021-11-12 07:13 UTC, ianikitin commented on js/main.js
> +dataLoad(loadToMarkers, showErrorMessage);
Да, номально.

2021-11-12 07:13 UTC, ianikitin commented on package.json
> +    "lodash": "4.17.21"
Если не пользуешься, то лучше удалить.

2021-11-12 18:16 UTC, merged